apiVersion: v1
kind: Template
metadata:
  name: libvirtd
labels:
  template: libvirtd

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "libvirtd"
    annotations:
      description: "A container running libvirtd"
      openshift.io/display-name: "libvirtd"
      iconClass: libvirtd
      tags: "libvirtd"
      openshift.io/provider-display-name: "Red Hat, Inc."
  spec: {}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "libvirtd"
  spec:
    triggers:
    - type: GitHub
    source:
      type: Git
      git:
        - uri: "https://github.com/lioramilbaum/CentOS-Dockerfiles.git"
        - ref: "master"
      contextDir: "CentOS-Dockerfiles/libvirtd/centos7"
    strategy:
      sourceStrategy:
        from:
          - kind: "ImageStreamTag"
          - namespace: "ember-csi"
          - name: centos/libvirtd:latest
      type: Source
    output:
      to:
        kind: ImageStreamTag
        name: centos/libvirtd:latest
