apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "ember-csi"
spec:
  replicas: 1
  triggers:
    type: ConfigChange
    type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
        - ember-csi
      from:
        kind: ImageStreamTag
        name: ember-csi
