kind: List
items:
  - apiVersion: "v1"
    kind: "BuildConfig"
    metadata:
      name: "libvirtd"
    spec:
      source:
        type: "Git"
        git:
          uri: "https://github.com/lioramilbaum/CentOS-Dockerfiles.git"
          ref: master
        contextDir: "libvirtd/centos7"
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: DockerImage
            name: centos/systemd
      output:
        to:
          kind: "ImageStreamTag"
          name: "libvirtd:latest"

  - apiVersion: "v1"
    kind: ImageStream
    metadata:
      name: libvirtd

  - apiVersion: "v1"
    kind: "BuildConfig"
    metadata:
      name: "ember-csi"
    spec:
      type: "Git"
      git:
        uri: "https://github.com/lioramilbaum/docker_images.git"
        ref: master
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: libvirtd/latest
      output:
        to:
          kind: "ImageStreamTag"
          name: "ember-csi:latest"

  - apiVersion: "v1"
    kind: ImageStream
    metadata:
      name: ember-csi
