kind: List
items:
  - apiVersion: "v1"
    kind: "BuildConfig"
    metadata:
      name: "libvirtd"
    spec:
      triggers:
      source:
        type: "Git"
        git:
          uri: "https://github.com/lioramilbaum/CentOS-Dockerfiles.git"
          ref: master
        contextDir: "libvirtd/centos7"
      strategy:
        type: "Custom"
        sourceStrategy:
          from:
            kind: "DockerImage"
            name: "centos/systemd"
      output:
        to:
          kind: "ImageStreamTag"
          name: "libvirtd:latest"

  - apiVersion: "v1"
    kind: ImageStream
    metadata:
    spec:
      dockerImageRepository: "docker.io/centos/systemd"
